### ISSUE TITLE
Package abandoned?

### ISSUE THREAD

**Issue by Matvik** [delagics/yii2-liqpay#1]
Composer says:
Package delagics/yii2-liqpay is abandoned, you should avoid using it. No replacement was suggested.
Is it true?

**Comment by insane-dev** [comment]
Hi. I just have no time to sync changes from [liqpay/sdk-php](https://github.com/liqpay/sdk-php) and apply my changes on top of it.

I will accept a pull request from anybody, that will sync original repo with this one. 
Then I will make package "Un-abandon".
